name: greetme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install packages at server
        run: cd api && npm ci

      - name: install packages and create build
        run: cd frontend && npm ci && npm run build

      - name: deploy to production
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl --request POST \
              --url https://api.render.com/v1/services/srv-ctm4s8i3esus739n77dg/deploys \
              --header 'accept: application/json' \
              --header 'Authorization: Bearer $RENDER_API_KEY' \
              --header 'content-type: application/json' \
              --data '
          {
            "clearCache": "clear",
          }
          '
