name: greetme

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Project
        run: |
          cd frontend
          npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: buildfiles
          path: ./frontend/dist

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: List available artifacts
        run: ls -R /home/runner/work

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: buildfiles
          path: ./api/public

      - name: Move files to correct location
        run: |
          mv ./api/public/buildfiles/* ./api/public/
          rm -r ./api/public/buildfiles

      - name: deploy to production
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "'$RENDER_SERVICE_ID'"}' \
          https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
